pipeline {
  agent none
  stages {
    stage('web-deploy') {
      agent {
        docker { image 'nginx:stable-alpine3.17-slim' }
      }
      steps {
        sh 'nginx -v'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
    stage('run hello world') {
      agent {
        docker { 
            image 'httpd:alpine3.18'
            
          
               }
      }
      steps {
        sh 'httpd -v'
      }
    }   
  }
}

